# @host=http://localhost:9999
@host=http://localhost:3000
# @host=https://localhost:3000
# @host=http://localhost:3002


###
POST {{host}}/clientes/1/transacoes
content-type: application/json

{
    "valor": 100,
    "tipo" : "d",
    "descricao" : "descricao"
}


###
GET {{host}}/clientes/1/extrato
content-type: application/json

###
GET http://localhost:4646/

# HTTP/1.1 200 OK
# Server: nginx/1.25.4
# Date: Tue, 20 Feb 2024 22:12:59 GMT
# Content-Type: application/json
# Content-Length: 108
# Connection: close

# {
#   "saldo": {
#     "data_extrato": "2024-02-20T22:12:59.52741293Z",
#     "limite": 100000,
#     "total": 0
#   },
#   "ultimas_transacoes": []
# }